name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: ${{ matrix.os }} for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - arm-unknown-linux-musleabihf
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
          - wasm32-unknown-unknown
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: target/x86_64-unknown-linux-musl/release/genact
            release_name: linux-x86_64
            cross: true
            strip: true
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            artifact_name: target/aarch64-unknown-linux-musl/release/genact
            release_name: linux-aarch64
            cross: true
            strip: false
          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
            artifact_name: target/armv7-unknown-linux-musleabihf/release/genact
            release_name: linux-armv7
            cross: true
            strip: false
          - os: ubuntu-latest
            target: arm-unknown-linux-musleabihf
            artifact_name: target/arm-unknown-linux-musleabihf/release/genact
            release_name: linux-arm
            cross: true
            strip: false
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: target/x86_64-pc-windows-msvc/release/genact.exe
            release_name: windows-x86_64.exe
            cross: false
            strip: true
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: target/x86_64-apple-darwin/release/genact
            release_name: macos-x86_64
            cross: false
            strip: true
          - os: ubuntu-latest
            target: wasm32-unknown-unknown

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - uses: actions-rs/install@v0.1
        with:
          crate: trunk
          version: latest
          use-tool-cache: true
        if: matrix.target == 'wasm32-unknown-unknown'

      - uses: actions-rs/install@v0.1
        with:
          crate: wasm-bindgen-cli
          version: latest
          use-tool-cache: true
        if: matrix.target == 'wasm32-unknown-unknown'

      - run: sudo apt install musl-tools
        if: matrix.os == 'ubuntu-latest' && matrix.target != 'wasm32-unknown-unknown'

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked --target=${{ matrix.target }}
          use-cross: ${{ matrix.cross }}
        if: matrix.target != 'wasm32-unknown-unknown'

      - name: trunk build
        run: trunk build --release
        if: matrix.target == 'wasm32-unknown-unknown'

      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          file: ${{ matrix.artifact_name }}
          args: --best --lzma
          strip: ${{ matrix.strip }}
        if: matrix.target != 'wasm32-unknown-unknown'

      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash
        if: matrix.target != 'wasm32-unknown-unknown'

      - name: Get CHANGELOG.md entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v1
        with:
          version: ${{ steps.tag.outputs.current_version }}
          path: ./CHANGELOG.md
        if: matrix.target != 'wasm32-unknown-unknown'

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact_name }}
          tag: ${{ github.ref }}
          asset_name: genact-$tag-${{ matrix.release_name }}
          body: ${{ steps.changelog_reader.outputs.log_entry }}
        if: matrix.target != 'wasm32-unknown-unknown'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
        if: matrix.target == 'wasm32-unknown-unknown'
